### ISSUE TITLE
node stop sync

### ISSUE THREAD

**Issue by c1989415123** [MetisProtocol/metis-replica-node#34]
### What Git revision / release tag are you using?

20240314-2

### What is your hardware specification?

Intel(R) Xeon(R) Gold 6354 CPU

### What Docker version are you using?

Docker version 23.0.1, build a5ee5b1

### What Linux distribution are you using?

Ubuntu 22.04.2 LTS

### Describe what the problem is?

my metis-replica-node update from 20220815 to 20240314-2，After being upgraded node stop sync

### If applicable, what are the logs from the server around the occurence of the problem?

l1dtl log

metis-l1dtl-1  | {"level":30,"time":1710487500110,"usingL2ChainId":1088,"latestBatch":{"index":1,"root":"0xc28358e8a457c9566b07ccc49c3c9f842b65c0b243203ecd90157743face6145","size":1,"prevTotalElements":1,"extraData":"0x","blockNumber":13641874,"timestamp":1637272859,"submitter":"0xcDf02971871B7736874E20B8487c019D28090019","l1TransactionHash":"0x8b1e0bc2200491376933800e8a90daa883a9da1bdacba65793a93f59629c36a4"},"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
metis-l1dtl-1  | {"level":30,"time":1710487500110,"highestSyncedL1Block":13642100,"targetL1Block":13642200,"highestSyncedL1BatchIndex":1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
metis-l1dtl-1  | {"level":30,"time":1710487500231,"chainId":1088,"parsedEvent":{"index":0,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece90000000000000000000000004200000000000000000000000000000000000011000000000000000000000000f3d58d1794f2634d6649a978f2dc093898feebc00000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000448269295400000000000000000000000013c74967aec876013d8fbf81485df780d6093527000000000000000000000000dd6ffc7d9a4fb420b637747edc6456340d12d37700000000000000000000000000000000000000000000000000000000","gasLimit":"1000000000","origin":"0x192E1101855bD523Ba69a9794e0217f0Db633510","blockNumber":13642181,"timestamp":1637276986,"ctcIndex":null},"msg":"Storing Event:"}
metis-l1dtl-1  | {"level":30,"time":1710487500233,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":2,"msg":"Processed events"}
metis-l1dtl-1  | {"level":50,"time":1710487500393,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:69:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:628:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:334:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}

l2geth log

metis-l2geth-1  | ERROR[03-15|07:13:16.129] handler blocksBeforeInsert get equeue err LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
metis-l2geth-1  | WARN [03-15|07:13:16.129] Synchronisation failed, retrying         err="element not found"l2geth

**Comment by mookim-eth** [comment]
same error `TypeError: Cannot read properties of null (reading 'from')` here:

```
# docker logs metis-replica-node-l1dtl-1
{"level":30,"time":1710488208274,"msg":"Service L1_Data_Transport_Service is starting..."}
{"level":30,"time":1710488208275,"msg":"Service L1_Data_Transport_Service is initializing..."}
{"level":30,"time":1710488208275,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1710488208281,"msg":"Service L1_Transport_Server is initializing..."}
{"level":30,"time":1710488208285,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
{"level":30,"time":1710488208285,"url":"http://65.108.198.24:8045","msg":"HTTP Server L1 RPC Provider initialized"}
{"level":30,"time":1710488208285,"url":"https://andromeda.metis.io","msg":"HTTP Server L2 RPC Provider initialized"}
{"level":30,"time":1710488208285,"msg":"Service L1_Transport_Server has initialized."}
{"level":30,"time":1710488208285,"msg":"Service L1_Ingestion_Service is initializing..."}
{"level":30,"time":1710488208287,"addressManager":"0x918778e825747a892b17C66fe7D24C618262867d","msg":"Using AddressManager"}
{"level":30,"time":1710488208352,"startingL1BlockNumber":13625200,"msg":"Starting sync"}
{"level":30,"time":1710488208368,"msg":"Service L1_Ingestion_Service has initialized."}
{"level":30,"time":1710488208368,"msg":"Service L1_Data_Transport_Service has initialized."}
{"level":30,"time":1710488208368,"msg":"Service L1_Transport_Server is starting..."}
{"level":30,"time":1710488208368,"msg":"Service L1_Ingestion_Service is starting..."}
{"level":30,"time":1710488208369,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
{"level":30,"time":1710488208369,"msg":"Service L1_Transport_Server can stop now"}
{"level":30,"time":1710488208373,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488208373,"highestSyncedL1Block":13625200,"targetL1Block":13626200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488250041,"fromL1Block":13625200,"toL1Block":13626200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488250195,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488250196,"highestSyncedL1Block":13626200,"targetL1Block":13627200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488290538,"fromL1Block":13626200,"toL1Block":13627200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488290680,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488290680,"highestSyncedL1Block":13627200,"targetL1Block":13628200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488330903,"fromL1Block":13627200,"toL1Block":13628200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488331041,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488331041,"highestSyncedL1Block":13628200,"targetL1Block":13629200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488369371,"fromL1Block":13628200,"toL1Block":13629200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488369502,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488369502,"highestSyncedL1Block":13629200,"targetL1Block":13630200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488407481,"fromL1Block":13629200,"toL1Block":13630200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488407616,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488407616,"highestSyncedL1Block":13630200,"targetL1Block":13631200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488447580,"fromL1Block":13630200,"toL1Block":13631200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488447720,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488447720,"highestSyncedL1Block":13631200,"targetL1Block":13632200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488486443,"fromL1Block":13631200,"toL1Block":13632200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488486567,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488486567,"highestSyncedL1Block":13632200,"targetL1Block":13633200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488529605,"fromL1Block":13632200,"toL1Block":13633200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488529724,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488529724,"highestSyncedL1Block":13633200,"targetL1Block":13634200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488572405,"fromL1Block":13633200,"toL1Block":13634200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488572554,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488572554,"highestSyncedL1Block":13634200,"targetL1Block":13635200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488611725,"fromL1Block":13634200,"toL1Block":13635200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488611864,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488611864,"highestSyncedL1Block":13635200,"targetL1Block":13636200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488652088,"fromL1Block":13635200,"toL1Block":13636200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488652224,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488652225,"highestSyncedL1Block":13636200,"targetL1Block":13637200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488691007,"fromL1Block":13636200,"toL1Block":13637200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488691160,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488691160,"highestSyncedL1Block":13637200,"targetL1Block":13638200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488730878,"fromL1Block":13637200,"toL1Block":13638200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488731063,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488731063,"highestSyncedL1Block":13638200,"targetL1Block":13639200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488768070,"fromL1Block":13638200,"toL1Block":13639200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488768217,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488768217,"highestSyncedL1Block":13639200,"targetL1Block":13640200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488808473,"fromL1Block":13639200,"toL1Block":13640200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488808624,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488808624,"highestSyncedL1Block":13640200,"targetL1Block":13641200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488846681,"fromL1Block":13640200,"toL1Block":13641200,"msg":"_syncInboxBatch get blocks"}
{"level":30,"time":1710488846823,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488846823,"highestSyncedL1Block":13641200,"targetL1Block":13642200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488846904,"chainId":1088,"parsedEvent":{"index":0,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece90000000000000000000000004200000000000000000000000000000000000011000000000000000000000000f3d58d1794f2634d6649a978f2dc093898feebc00000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000448269295400000000000000000000000013c74967aec876013d8fbf81485df780d6093527000000000000000000000000dd6ffc7d9a4fb420b637747edc6456340d12d37700000000000000000000000000000000000000000000000000000000","gasLimit":"1000000000","origin":"0x192E1101855bD523Ba69a9794e0217f0Db633510","blockNumber":13642181,"timestamp":1637276986,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1710488846905,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":1,"msg":"Processed events"}
{"level":50,"time":1710488847073,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:69:32)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:628:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:334:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}
{"level":30,"time":1710488907076,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488907076,"highestSyncedL1Block":13641200,"targetL1Block":13642200,"highestSyncedL1BatchIndex":-1,"startingL1BatchIndex":{"type":"BigNumber","hex":"0xa697"},"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1710488907168,"chainId":1088,"parsedEvent":{"index":0,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece90000000000000000000000004200000000000000000000000000000000000011000000000000000000000000f3d58d1794f2634d6649a978f2dc093898feebc00000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000448269295400000000000000000000000013c74967aec876013d8fbf81485df780d6093527000000000000000000000000dd6ffc7d9a4fb420b637747edc6456340d12d37700000000000000000000000000000000000000000000000000000000","gasLimit":"1000000000","origin":"0x192E1101855bD523Ba69a9794e0217f0Db633510","blockNumber":13642181,"timestamp":1637276986,"ctcIndex":null},"msg":"Storing Event:"}
{"level":30,"time":1710488907168,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":1,"msg":"Processed events"}
{"level":50,"time":1710488907284,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:69:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:628:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:334:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}
```

**Comment by mookim-eth** [comment]
found the code of dtl, not sure which commit you build the image
https://github.com/MetisProtocol/mvm/blob/d7e68aa88753350bc117b3701f9af26a00692702/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts#L68

i guess this `l1Transaction` is null

**Comment by ericlee42** [comment]
Can you update your compose and env files without private information here?

**Comment by mookim-eth** [comment]
> Can you update your compose and env files without private information here?

no change to compose file, and env only include a L1 rpc, if you need i can set up a cloudflare forward

**Comment by mookim-eth** [comment]
confirmed that l1Transaction is indeed null:

clone https://github.com/MetisProtocol/mvm and edit `packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts` to include console.log, then `dockcer build --target data-transport-layer -f ./ops/docker/Dockerfile . -t dtl`

```
{"level":30,"time":1710558573926,"eventName":"TransactionEnqueued","numEvents":1,"durationMs":0,"msg":"Processed events"}
l1Transaction: null event: {
  blockNumber: 13641777,
  blockHash: '0x41b649cfaaf59c1febb5ca394212c44305157d8904c27e800c3a16bb13e484c6',
  transactionIndex: 132,
  removed: false,
  address: '0x56a76bcC92361f6DF8D75476feD8843EdC70e1C9',
  data: '0x0000000000000000000000000000000000000000000000000000000000000440000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001',
  topics: [
    '0x178ecbc4b986ebf7ea68a0a7ae593212f963053458fda23484ad60e95dde758d'
  ],
  transactionHash: '0xd0a2d3c037da443cdf5eb1f8e446391a2ceb5bb777418915ba91c8b077be37d7',
  logIndex: 190,
  removeListener: [Function (anonymous)],
  getBlock: [Function (anonymous)],
  getTransaction: [Function (anonymous)],
  getTransactionReceipt: [Function (anonymous)],
  event: 'SequencerBatchAppended',
  eventSignature: 'SequencerBatchAppended(uint256,uint256,uint256,uint256)',
  decode: [Function (anonymous)],
  args: [
    BigNumber { _hex: '0x0440', _isBigNumber: true },
    BigNumber { _hex: '0x00', _isBigNumber: true },
    BigNumber { _hex: '0x00', _isBigNumber: true },
    BigNumber { _hex: '0x01', _isBigNumber: true },
    _chainId: BigNumber { _hex: '0x0440', _isBigNumber: true },
    _startingQueueIndex: BigNumber { _hex: '0x00', _isBigNumber: true },
    _numQueueElements: BigNumber { _hex: '0x00', _isBigNumber: true },
    _totalElements: BigNumber { _hex: '0x01', _isBigNumber: true }
  ]
}
{"level":50,"time":1710558574015,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:70:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:628:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:334:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}
```

**Comment by mookim-eth** [comment]
found the reason, my L1 RPC (eth-docker) pruned txhash=>tx relation, so getTransaction failed and return `null`, will come up with a fix using `getBlock` soon

**Comment by ericlee42** [comment]
Please use non-pruned eth client instread.
