### ISSUE TITLE
L1 DTL crashes with message: TypeError: Cannot read properties of null (reading 'from')"

### ISSUE THREAD

**Issue by northwestnodes-eric** [MetisProtocol/metis-replica-node#36]
### What Git revision / release tag are you using?

latest

### What is your hardware specification?

N/A

### What Docker version are you using?

latest

### What Linux distribution are you using?

Ubuntu 22.04

### Describe what the problem is?

After a while the l1dtl stops syncing and crashes with the following error:
```
l1dtl-1   | {"level":30,"time":1710491968771,"msg":"Service L1_Data_Transport_Service is starting..."}
l1dtl-1   | {"level":30,"time":1710491968771,"msg":"Service L1_Data_Transport_Service is initializing..."}
l1dtl-1   | {"level":30,"time":1710491968771,"msg":"Initializing L1 Data Transport Service..."}
l1dtl-1   | {"level":30,"time":1710491968798,"msg":"Service L1_Transport_Server is initializing..."}
l1dtl-1   | {"level":30,"time":1710491968801,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
l1dtl-1   | {"level":30,"time":1710491968801,"url":"(...)","msg":"HTTP Server L1 RPC Provider initialized"}
l1dtl-1   | {"level":30,"time":1710491968801,"url":"https://andromeda.metis.io","msg":"HTTP Server L2 RPC Provider initialized"}
l1dtl-1   | {"level":30,"time":1710491968801,"msg":"Service L1_Transport_Server has initialized."}
l1dtl-1   | {"level":30,"time":1710491968801,"msg":"Service L1_Ingestion_Service is initializing..."}
l1dtl-1   | {"level":30,"time":1710491968805,"addressManager":"0x918778e825747a892b17C66fe7D24C618262867d","msg":"Using AddressManager"}
l1dtl-1   | {"level":30,"time":1710491970143,"startingL1BlockNumber":13625200,"msg":"Starting sync"}
l1dtl-1   | {"level":30,"time":1710491970307,"msg":"Service L1_Ingestion_Service has initialized."}
l1dtl-1   | {"level":30,"time":1710491970307,"msg":"Service L1_Data_Transport_Service has initialized."}
l1dtl-1   | {"level":30,"time":1710491970308,"msg":"Service L1_Transport_Server is starting..."}
l1dtl-1   | {"level":30,"time":1710491970308,"msg":"Service L1_Ingestion_Service is starting..."}
l1dtl-1   | {"level":30,"time":1710491970310,"host":"127.0.0.1","port":7878,"msg":"Server started and listening"}
l1dtl-1   | {"level":30,"time":1710491970312,"msg":"Service L1_Transport_Server can stop now"}
l1dtl-1   | {"level":30,"time":1710491970477,"usingL2ChainId":1088,"latestBatch":null,"stateLatestBatch":null,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
l1dtl-1   | {"level":30,"time":1710491970477,"highestSyncedL1Block":13641770,"targetL1Block":13641870,"highestSyncedL1BatchIndex":-1,"inboxAddress":"0xff00000000000000000000000000000000001088","inboxSender":"0x1a9da0aeda630ddf2748a453bf6d92560762d914","inboxBatchStart":42647,"useBatchInbox":false,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
l1dtl-1   | {"level":50,"time":1710491972321,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/handlers/sequencer-batch-appended.ts:69:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:628:29)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:334:11)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}
```

Nothing else.

l1geth continues as normal.

**Comment by ericlee42** [comment]
Can you update your compose and env files without private information here?

**Comment by northwestnodes-eric** [comment]
We are at latest posted configs (the latest "release"). I think it might have something to do with the blocks/logs per interval? Is there some sort of racing condition there?

We've removed chaindata and are re-syncing... keep you posted in a few hours.

**Comment by northwestnodes-eric** [comment]
l2geth crashes while syncing, corrupt leveldb. This is on top of the l1dtl error posted in this thread.

**Comment by ericlee42** [comment]
I have tried many times, I can't replicate the error.

**Comment by northwestnodes-eric** [comment]
>"I have tried many times, I can't replicate the error."
>proceeds to merge a PR by random dev
>marks it as fixed

Thanks @mookim-eth

**Comment by ericlee42** [comment]
You did not read the upgrade guide.

the guide mentioned that you should have a non-pruned eth client.

**Comment by northwestnodes-eric** [comment]
@ericlee42 The eth client is not pruned.

**Comment by artjoma** [comment]
Similar issue:
```
2a9682cd1959e720e175e77d36c","s":"0x4cbb88077218c8ffe15c3c347f21eae09c0843e3be084b86be78e9459aa23664"}},"confirmed":true,"seqSign":null},{"index":12876642,"batchIndex":41202,"blockNumber":19099826,"timestamp":1706381750,"gasLimit":"0","target":"0x0000000000000000000000000000000000000000","origin":null,"data":"0xf8ad819e8502e90edd008304aa4994652a63c4df14e29080ab058d6f151aba61f86c1080b84447e7ef240000000000000000000000004febd4ea737a0ae94dd56e754e9b7a83e1c459e900000000000000000000000000000000000000000000027eff4b6db11c846ca68208a3a02a20e7acc3913eb9f90f1f418586f1279d1ec235f3e503286278ff16d5d5a1b6a07c69a4719945860550820e0901a4b1be0273d29ecb97425ae271ba495c2970df","queueOrigin":"sequencer","value":"0x0","queueIndex":null,"decoded":{"nonce":"158","gasPrice":"12500000000","gasLimit":"305737","value":"0x0","target":"0x652a63c4df14e29080ab058d6f151aba61f86c10","data":"0x47e7ef240000000000000000000000004febd4ea737a0ae94dd56e754e9b7a83e1c459e900000000000000000000000000000000000000000000027eff4b6db11c846ca6","sig":{"v":0,"r":"0x2a20e7acc3913eb9f90f1f418586f1279d1ec235f3e503286278ff16d5d5a1b6","s":"0x7c69a4719945860550820e0901a4b1be0273d29ecb97425ae271ba495c2970df"}},"confirmed":true,"seqSign":null}]},"msg":"Storing Event:"}
l1dtl_1  | {"level":30,"time":1711470638139,"eventName":"SequencerBatchAppended","numEvents":1,"durationMs":4440,"msg":"Processed events"}
l1dtl_1  | {"level":30,"time":1711470638145,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
l1dtl_1  | {"level":30,"time":1711470638145,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 19100000, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
l1dtl_1  | {"level":30,"time":1711470638153,"msg":"Reading from local Proxy__MVM_CanonicalTransaction, chainId is 1"}
l1dtl_1  | {"level":30,"time":1711470638153,"msg":"Read cached contract address for Proxy__MVM_CanonicalTransaction from 0 to 19100000, get 0x6A1DB7d799FBA381F2a518cA859ED30cB8E1d41a"}
l1dtl_1  | {"level":30,"time":1711470638162,"chainId":1088,"parsedEvent":{"index":41202,"chainId":1088,"batchIndex":41202,"shouldStartAtElement":12875417,"totalElementsToAppend":1226,"txBatchSize":962088,"txBatchTime":1706381800540,"root":"0xa85fab466643b493432ec186e7d773796b2a23ea23b6adaf9af0ecb4ba9c6221","l1BlockNumber":19099902,"timestamp":1706382527},"msg":"Storing Event:"}
l1dtl_1  | {"level":30,"time":1711470638163,"eventName":"AppendBatchElement","numEvents":1,"durationMs":4,"msg":"Processed events"}
l1dtl_1  | {"level":30,"time":1711470642691,"fromL1Block":19099900,"toL1Block":19100000,"msg":"_syncInboxBatch get blocks"}
l1dtl_1  | {"level":50,"time":1711470642704,"extra":{"message":"TypeError: Cannot read properties of null (reading 'transactions')","stack":"TypeError: Cannot read properties of null (reading 'transactions')\n    at L1IngestionService._syncInboxBatch (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:477:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:360:9)\n    at L1IngestionService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at async Promise.all (index 1)\n    at L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:148:7)\n    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:72:5)\n    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:78:5)"},"msg":"Caught an unhandled error"}
```
