### ISSUE TITLE
Blocks is not iterable

### ISSUE THREAD

**Issue by northwestnodes-eric** [MetisProtocol/metis-replica-node#44]
### What Git revision / release tag are you using?

latest

### What is your hardware specification?

N/A

### What Docker version are you using?

latest

### What Linux distribution are you using?

Ubuntu 22.04

### Describe what the problem is?

When syncing, the DTL layer suddenly stops and gets stuck on block `15363388`. 

### If applicable, what are the logs from the server around the occurence of the problem?

```
dtl-1  | {"level":30,"time":1711142329174,"fromBlock":15363388,"toBlock":15423388,"msg":"Synchronizing unconfirmed transactions from Layer 2 (Metis)"}
```

and

```
dtl-1  | {"level":50,"time":1711142329189,"extra":{"message":"TypeError: blocks is not iterable","stack":"TypeError: blocks is not iterable\n    at L2IngestionService._syncSequencerBlocks (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:146:29)\n    at async L2IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l2-ingestion/service.js:84:17)\n    at async L2IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async Promise.all (index 2)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:64:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:76:9"},"msg":"Caught an unhandled error"}
```

**Comment by ericlee42** [comment]
You're not using correct dtl configuration.

the l2dtl has been deprecated but you are using it.

please refer to upgrade guide to upgrade your node.
