### ISSUE TITLE
panic: Refund counter below zero (gas: 4800 > refund: 0)

### ISSUE THREAD

**Issue by northwestnodes-eric** [MetisProtocol/metis-replica-node#45]
### What Git revision / release tag are you using?

latest

### What is your hardware specification?

N/A

### What Docker version are you using?

latest

### What Linux distribution are you using?

Ubuntu 22.04

### Describe what the problem is?

While syncing with `GCMODE=archive` getting the following error on two nodes:

`panic: Refund counter below zero (gas: 4800 > refund: 0)`

```
l2geth-1  | panic: Refund counter below zero (gas: 4800 > refund: 0)
l2geth-1  |
l2geth-1  | goroutine 417 [running]:
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/state.(*StateDB).SubRefund(0xc0044d8d80, 0x12c0)
l2geth-1  |     /l2geth/core/state/statedb.go:224 +0xdc
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.init.makeGasSStoreFunc.func12(0xc0021f4008, 0xc000a16900, 0xc002dd6ac8, 0xc0024b0bf8?, 0xc002dd6ac8?)
l2geth-1  |     /l2geth/core/vm/operations_acl.go:73 +0x49c
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc0021f8008, 0xc000a16900, {0xc0058f63e4, 0x44, 0x19c}, 0x0)
l2geth-1  |     /l2geth/core/vm/interpreter.go:261 +0x86e
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc0021f4008, 0xc000a16900, {0xc0058f63e4, 0x44, 0x19c}, 0x0)
l2geth-1  |     /l2geth/core/vm/evm.go:75 +0x37f
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc0021f4008, {0x1365fa0, 0xc000a166c0}, {0xde, 0xad, 0xde, 0xad, 0xde, 0xad, 0xde, ...}, ...)
l2geth-1  |     /l2geth/core/vm/evm.go:256 +0x8b3
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc0021f4008?, 0xc0021f8008, 0xc000a166c0, 0xc005723b20, 0xc00231c9f0)
l2geth-1  |     /l2geth/core/vm/instructions.go:771 +0x308
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc0021f8008, 0xc000a166c0, {0xc0000410e0, 0x44, 0x44}, 0x0)
l2geth-1  |     /l2geth/core/vm/interpreter.go:277 +0xa96
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc0021f4008, 0xc000a166c0, {0xc0000410e0, 0x44, 0x44}, 0x0)
l2geth-1  |     /l2geth/core/vm/evm.go:75 +0x37f
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc0021f4008, {0x13657e0, 0xc000749968}, {0x45, 0xa0, 0x1e, 0x4e, 0x4, 0xf1, 0x4f, ...}, ...)
l2geth-1  |     /l2geth/core/vm/evm.go:256 +0x8b3
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDbWithBlockNumber(0xc0019fc850, 0x0)
l2geth-1  |     /l2geth/core/state_transition.go:303 +0xb1b
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDb(...)
l2geth-1  |     /l2geth/core/state_transition.go:238
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.ApplyMessage(0x10b1640?, {0x1374c98?, 0xc003efd830?}, 0x569851995fbf9163?)
l2geth-1  |     /l2geth/core/state_transition.go:164 +0x25
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.precacheTransaction(_, {_, _}, _, _, _, _, _, {0x0, {0x0, ...}, ...})
l2geth-1  |     /l2geth/core/state_prefetcher.go:83 +0x225
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.(*statePrefetcher).Prefetch(_, _, _, {0x0, {0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
l2geth-1  |     /l2geth/core/state_prefetcher.go:64 +0x2b4
l2geth-1  | github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh.func2({0xc17872166a55c6c1?, 0x305035037?, 0x1af0620?})
l2geth-1  |     /l2geth/core/blockchain.go:2083 +0x13c
l2geth-1  | created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh in goroutine 421
l2geth-1  |     /l2geth/core/blockchain.go:2081 +0x1b98
```

Primary node got stuck on block `10315885` and secondary node got stuck on block `4911058` both crashing with the aforementioned error. Fresh syncs. l2geth isn't syncing and crashing, l1dtl is still going strong.

**Comment by northwestnodes-eric** [comment]
I'd love to use a snapshot but your link expired. Can you post the actual URLs to snapshots instead of just the file names, or is this like an internet mystery where we hunt down links to snapshots and there's a price at the end?

**Comment by ericlee42** [comment]
It's not a file name.

fyi https://docs.aws.amazon.com/ebs/latest/userguide/ebs-snapshots.html

reopen this issue until the bug is fixed

**Comment by northwestnodes-eric** [comment]
What does an AWS manual have to do with anything?

Please give me a link to the snapshots you require me to sync from. The l2geth snapshot and the l1dtl snapshot.

**Comment by ericlee42** [comment]
@northwestnodes-eric 

Do you have `GCMODE` env for your l2geth?

if you don't have the env or use `full` mode, you need to add `--cache.noprefetch=true` arguement to your l2geth.


```yaml
  l2geth:
    command: ["--cache.noprefetch=true"]
```
