### ISSUE TITLE
New "metisdao" images problematic

### ISSUE THREAD

**Issue by letsbangout** [MetisProtocol/metis-replica-node#47]
I was instructed to use l2geth 0.0.4 in another bug report.  I modified the existing docker-compose which was running "ericlee42/metis:dtl-4" and started l2geth with an empty data directory as instructed.  It seemed to stop syncing at some point.

Figuring I might need a newer L1, I grabbed the latest release, "metis-replica-node-20240321".  I set the l2geth image to metisdao/l2geth-v0.0.4 as previously instructed.  I stopped all containers and wiped the old ones with 'docker container prune'.  Then I brought up the containers, but an error resulted in l1dtl.  I do not have a capture of the exact log, but on the console it appears as:

dependency failed to start: container metis-replica-node-20240321-l1dtl-1 is unhealthy

I tried updating l1dtl to v0.1.1 in the docker-compose, and I got another error which I did capture via the logs:

Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
TypeError: Cannot read properties of null (reading 'getCode')
    at L1IngestionService._init (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:153:49)
    at L1IngestionService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
    at L1DataTransportService._init (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:139:7)
    at L1DataTransportService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:68:5)
    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)
{"level":30,"time":1712380306676,"msg":"Service L1_Data_Transport_Service is starting..."}
{"level":30,"time":1712380306677,"msg":"Service L1_Data_Transport_Service is initializing..."}
{"level":30,"time":1712380306678,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1712380306720,"msg":"Service L1_Transport_Server is initializing..."}
{"level":30,"time":1712380306739,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
{"level":40,"time":1712380306739,"msg":"HTTP Server L1 RPC Provider not initialized"}
{"level":30,"time":1712380306739,"url":"https://andromeda.metis.io","msg":"HTTP Server L2 RPC Provider initialized"}
{"level":30,"time":1712380306739,"msg":"Service L1_Transport_Server has initialized."}
{"level":30,"time":1712380306739,"msg":"Service L1_Ingestion_Service is initializing..."}
{"level":30,"time":1712380306840,"addressManager":"0x918778e825747a892b17C66fe7D24C618262867d","msg":"Using AddressManager"}
Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
TypeError: Cannot read properties of null (reading 'getCode')
    at L1IngestionService._init (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:153:49)
    at L1IngestionService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
    at L1DataTransportService._init (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:139:7)
    at L1DataTransportService.init (/opt/optimism/packages/common-ts/src/base-service.ts:55:5)
    at L1DataTransportService.start (/opt/optimism/packages/common-ts/src/base-service.ts:68:5)
    at <anonymous> (/opt/optimism/packages/data-transport-layer/src/services/run.ts:79:5)

So apparently I can not get any of these l1dtl images to launch, and I am completely unsure how to run l2geth 0.0.4, or even how to run a replica node at all.  It seems this has gotten more complicated (needlessly?) with the passing of time.

**Comment by ericlee42** [comment]
> HTTP Server L1 RPC Provider not initialized

be sure that you have a correct eth rpc
