### ISSUE TITLE
L2geth panic

### ISSUE THREAD

**Issue by artjoma** [MetisProtocol/metis-replica-node#48]
### What Git revision / release tag are you using?

l2geth 3159aa16c93c865327b7d5b94705ab66cf84b8ae

### What is your hardware specification?

Dedicated server

### What Docker version are you using?

20.10.21

### What Linux distribution are you using?

ubuntu server 22.04, 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Describe what the problem is?

L2geth panic when sync node from scratch
```
INFO [04-08|06:11:21.264] Starting peer-to-peer node               instance=Geth/v1.9.10-stable/linux-amd64/go1.20.14
INFO [04-08|06:11:21.264] Allocated trie memory caches             clean=2.00GiB dirty=0.00B
INFO [04-08|06:11:21.264] Allocated cache and file handles         database=/home/blockchain/metis-mainnet/l2geth/chaindata/geth/chaindata cache=2.00GiB handles=262144
INFO [04-08|06:11:22.053] Opened ancient database                  database=/home/blockchain/metis-mainnet/l2geth/chaindata/geth/ancient
INFO [04-08|06:11:22.053] Initialised chain configuration          config="{ChainID: 1088 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: 3380000, Engine: clique}"
INFO [04-08|06:11:22.054] Initialising Ethereum protocol           versions="[64 63]" network=1088 dbversion=7
INFO [04-08|06:11:22.054] Loaded most recent local header          number=5480391 hash=c2f7bd…5d680b td=10960783 age=11mo2w3d
INFO [04-08|06:11:22.054] Loaded most recent local full block      number=5480391 hash=c2f7bd…5d680b td=10960783 age=11mo2w3d
INFO [04-08|06:11:22.054] Loaded most recent local fast block      number=5480391 hash=c2f7bd…5d680b td=10960783 age=11mo2w3d
INFO [04-08|06:11:22.110] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-08|06:11:22.110] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-08|06:11:22.110] Running in sequencer mode                sync-backend=l1
INFO [04-08|06:11:22.110] Fees                                     threshold-up=nil threshold-down=nil
INFO [04-08|06:11:22.110] Enforce Fees                             set=false
INFO [04-08|06:11:22.110] Configured rollup client                 url=http://127.0.0.1:7878 chain-id=1088 ctc-deploy-height=13626959
INFO [04-08|06:11:22.110] Configured seqAdapter                    url=                      SeqsetContract=0x0fe382b74C3894B65c10E5C12ae60Bbd8FAf5b48 SeqsetValidHeight=15214531 SeqAddress= LocalL2ClientHttp=http://localhost:8545
INFO [04-08|06:11:22.110] Start sync service only peer             bridge=https://andromeda.metis.io
INFO [04-08|06:11:22.110] initializeLatestL1                       ctcDeployHeight=13626959
INFO [04-08|06:11:22.110] Found latest index                       index=5479434
INFO [04-08|06:11:22.110] Found latest queue index                 queue-index=26383
INFO [04-08|06:11:22.133] Found correct staring queue index        queue-index=26383
INFO [04-08|06:11:22.133] Initialized Latest L1 Info               blocknumber=17133559 timestamp=1682550636
INFO [04-08|06:11:22.133] Initial Rollup State                     state=0xbe1b91923b9bf62f4847b109c530ea04ec13cf6eddd8b572eaf60bff8dcdef21 index=5479434 queue-index=26383 verified-index=5479434
INFO [04-08|06:11:22.133] Backend Config                           max-calldata-size=40000 gas-limit=1100000000 is-verifier=false using-ovm=true ctx.ExtRPCEnabled() =true
INFO [04-08|06:11:22.134] Dial to a new proxy rpc client           url=https://andromeda.metis.io
INFO [04-08|06:11:22.164] New local node record                    seq=342 id=0eba8ad83a02f6ee ip=127.0.0.1 udp=30309 tcp=30309
INFO [04-08|06:11:22.164] Started P2P networking                   self=enode://c224d1ddb10873a5e15292b2cd976d53ca549a772f3c7655f6d6cb18ae17b1af0bbc5621715a569130bf162c3b06363ae290b7d8115015a47adda1251bbf42a8@127.0.0.1:30309
INFO [04-08|06:11:22.165] IPC endpoint opened                      url=/home/blockchain/metis-mainnet/l2geth/chaindata/geth.ipc
INFO [04-08|06:11:22.165] HTTP endpoint opened                     url=http://0.0.0.0:8595        cors=* vhosts=*
INFO [04-08|06:11:22.165] WebSocket endpoint opened                url=ws://[::]:28549
INFO [04-08|06:11:30.625] New local node record                    seq=343 id=0eba8ad83a02f6ee ip=162.19.170.89 udp=30309 tcp=30309
INFO [04-08|06:16:02.164] Block synchronisation started 
panic: Refund counter below zero (gas: 4800 > refund: 0)

goroutine 16795 [running]:
github.com/ethereum-optimism/optimism/l2geth/core/state.(*StateDB).SubRefund(0xc0019ae7e0, 0x12c0)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state/statedb.go:224 +0xe9
github.com/ethereum-optimism/optimism/l2geth/core/vm.makeGasSStoreFunc.func1(0xc001e70000, 0xc001af6480, 0xc001af6480?, 0xc007e4cde0?, 0xc0023eb1d0?)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/operations_acl.go:73 +0x4df
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc001e78000, 0xc001af6480, {0xc002422124, 0x44, 0x19c}, 0x0)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/interpreter.go:261 +0x8ae
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc001e70000, 0xc001af6480, {0xc002422124, 0x44, 0x19c}, 0x61?)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/evm.go:75 +0x39f
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc001e70000, {0x1368e40, 0xc0019b2480}, {0xde, 0xad, 0xde, 0xad, 0xde, 0xad, 0xde, ...}, ...)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/evm.go:256 +0x8b9
github.com/ethereum-optimism/optimism/l2geth/core/vm.opCall(0xc001e70000?, 0xc001e78000, 0xc0019b2480, 0xc001e391c0, 0xc001e6aaf8)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/instructions.go:771 +0x32a
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVMInterpreter).Run(0xc001e78000, 0xc0019b2480, {0xc007df2000, 0x44, 0x44}, 0x0)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/interpreter.go:277 +0xaff
github.com/ethereum-optimism/optimism/l2geth/core/vm.run(0xc001e70000, 0xc0019b2480, {0xc007df2000, 0x44, 0x44}, 0x23?)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/evm.go:75 +0x39f
github.com/ethereum-optimism/optimism/l2geth/core/vm.(*EVM).Call(0xc001e70000, {0x136b280, 0xc0097e6d50}, {0x45, 0xa0, 0x1e, 0x4e, 0x4, 0xf1, 0x4f, ...}, ...)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/vm/evm.go:256 +0x8b9
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDbWithBlockNumber(0xc0093a1810, 0x0)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state_transition.go:303 +0xb1e
github.com/ethereum-optimism/optimism/l2geth/core.(*StateTransition).TransitionDb(...)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state_transition.go:238
github.com/ethereum-optimism/optimism/l2geth/core.ApplyMessage(0x10e0880?, {0x1377e80?, 0xc00265f0e0?}, 0x569851995fbf9163?)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state_transition.go:164 +0x2c
github.com/ethereum-optimism/optimism/l2geth/core.precacheTransaction(_, {_, _}, _, _, _, _, _, {0x0, {0x0, ...}, ...})
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state_prefetcher.go:83 +0x24f
github.com/ethereum-optimism/optimism/l2geth/core.(*statePrefetcher).Prefetch(_, _, _, {0x0, {0x0, 0x0}, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/state_prefetcher.go:64 +0x2be
github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh.func2({0xc17d00c94daa695d?, 0x421e6607d1?, 0x1aaaf40?})
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/blockchain.go:2091 +0x14a
created by github.com/ethereum-optimism/optimism/l2geth/core.(*BlockChain).insertChainWithFuncAndCh
        /builds/parsiqio/blockchain/parsiq-metis-mvm/l2geth/core/blockchain.go:2089 +0x1afc
```

Dtl version: 0.0.2
L2geth version: commit 3159aa16c93c865327b7d5b94705ab66cf84b8ae

l2get start.sh
```
export NO_USB=true
export IPC_DISABLE=false
export MAX_PEER=150
export DATADIR=/home/blockchain/metis-mainnet/l2geth/chaindata

export USING_OVM=true
export CHAIN_ID=1088
export NETWORK_ID=1088
export TARGET_GAS_LIMIT=1100000000

export GCMODE=archive
export ETH1_CTC_DEPLOYMENT_HEIGHT=13626959
export ETH1_SYNC_SERVICE_ENABLE=false

export ROLLUP_BACKEND=l1
export ROLLUP_MAX_CALLDATA_SIZE=40000
export ROLLUP_POLL_INTERVAL_FLAG=10s
export ROLLUP_TIMESTAMP_REFRESH=10s
#export ROLLUP_ENFORCE_FEES=true

# for geth.sh
export ROLLUP_STATE_DUMP_PATH=https://metisprotocol.github.io/metis-networks/andromeda-mainnet/state-dump.latest.json
export BLOCK_SIGNER_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
export BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F
export ROLLUP_CLIENT_HTTP=http://127.0.0.1:7878

export RPC_ADDR=0.0.0.0
export RPC_API=eth,rollupbridge,web3,debug
export RPC_CORS_DOMAIN=*
export RPC_ENABLE=true
export RPC_PORT=8595
export RPC_VHOSTS=*
export RPC_GAS_CAP=11000000
export RPC_WRITE_TIMEOUT=5m
export USING_OVM=true
export WS_ADDR=0.0.0.0
export WS_API=eth,rollupbridge,web3,debug
export WS_ORIGINS=*
export WS=true

export SEQSET_VALID_HEIGHT=15214531
export DESEQBLOCK=0
export SEQSET_CONTRACT=0x0fe382b74C3894B65c10E5C12ae60Bbd8FAf5b48
export SEQ_BRIDGE_URL=https://andromeda.metis.io
export BOOTNODES=enode://61b617d2549296b0b950efcf8c1d87227d454d44362e642dde37d83092a445f2b6a6fd651d611b2893249d1e9d15c8f1d4b067142cff53280a08c9c7565c29e2@3.22.33.68:30303,enode://524e335aaa2a4555fe2d54f07fc34da83d80b0407d86c606b76ce918f96a348cf91947f7c60b0eabd29f68d2669cc0ced1360636daa53d0ccc948e154d0ce21e@3.129.121.37:30303,enode://c4cc213e3c5cb57b1ea6e1aa0b8a28240b03a5fa4b65ff08c53faf448182ae161d68c78fe48040da1e5d9087c6f19b60644605c4c2d78845627f09b90207e56c@3.17.198.212:30303

./geth \
 --datadir=$DATADIR \
 --datadir.ancient="./ancient" \
 --wsport=28549 \
 --cache=4096 \
 --port=30309 \
 --syncmode full \
 --nat "any"

```

**Comment by yorickdowne** [comment]
Thou must `GCMODE=archive` for l2geth. We had the same issues when that wasn't set.

**Comment by ericlee42** [comment]
btw, I don't see the bootnode argument in the geth command, you need to add it

**Comment by artjoma** [comment]
> I'm facing this same issue, even using a snapshot on latest v0.1.2

For me only works if:
```
export GCMODE=archive
geth  --syncmode fast \
```

only this combination of sync+gcmode parameters
